#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    sonokai_style = 'andromeda'
    sonokai_enable_italic = 1
    sonokai_disable_italic_comment = 1
    colorscheme = "sonokai"
    colorscheme_bg = "dark"
    # colorscheme = "hybrid"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = 1
    enable_statusline_mode = true
    spacevim_enable_vimfiler_welcome = 0
    realtime_leader_guide = 1
    default_indent = 2
    enable_statusline_mode = true
    bootstrap_after = "myspacevim#after"
    bootstrap_before = "myspacevim#before"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "smart"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "default"

[[layers]]
  name = "git"

[[layers]]
  name = "fzf"

[[layers]]
  name = "sudo"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "lang#haskell"

[[layers]]
  name = "tools#dash"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "sudo"

[[layers]]
  name = "tmux"

[[layers]]
  name = "lang#go"

[[custom_plugins]]
  name = "flazz/vim-colorschemes"
  merged = 0
[[layers]]
    name = 'core#statusline'
    enable = true
[[layers]]
    name = 'core#tabline'
    enable = true
[[custom_plugins]]
 name = 'tweekmonster/startuptime.vim'
 merged = 0


# Adding some colorschemes
[[custom_plugins]]
  name = 'rafi/awesome-vim-colorschemes.git'
  merged = 0

[[custom_plugins]]
  name = 'arzg/vim-colors-xcode.git'
  merged = 0
  
